/**
 * Boxing Center — Bootstrap Bothosting
 *
 * Sur Bothosting : renommez ce fichier en index.js à la racine du projet Node.js.
 * Il clone boxing-center-bot, génère le .env depuis les variables Bothosting,
 * installe les dépendances et démarre le bot (PM2 ou Node).
 */

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const GITHUB_REPO_URL =
    process.env.BOT_GITHUB_REPO || 'https://github.com/angoularaphael/boxing-center-bot.git';
const APP_DIR_NAME = process.env.BOT_APP_DIR || 'boxing-center-bot-app';
const APP_DIR = path.join(__dirname, APP_DIR_NAME);
const PM2_APP_NAME = process.env.PM2_APP_NAME || 'boxing-center-bot';

const ENV_KEYS = [
    'PORT',
    'NODE_ENV',
    'SUPABASE_URL',
    'SUPABASE_SERVICE_ROLE_KEY',
    'SUPABASE_ANON_KEY',
    'SITE_API_SECRET',
    'ADMIN_PASSWORD',
    'SUPER_ADMIN_EMAIL',
    'SUPER_ADMIN_PASSWORD',
    'JWT_SECRET',
    'CORS_ORIGIN',
    'MANDATORY_ADMIN_PHONE',
    'BOXING_CENTER_SITE_URL',
    'BREVO_API_KEY',
    'BREVO_SENDER_EMAIL',
    'BREVO_SENDER_NAME',
];

const DEFAULTS = {
    PORT: '3002',
    NODE_ENV: 'production',
    SUPABASE_URL: 'https://ulxtbvxdueolvnjhpzvw.supabase.co',
    SUPER_ADMIN_EMAIL: 'angoularaphael05@gmail.com',
    MANDATORY_ADMIN_PHONE: '237693646080',
    BOXING_CENTER_SITE_URL: 'https://boxingcenter.fr/',
    BREVO_SENDER_EMAIL: 'boxingcenter31@gmail.com',
    BREVO_SENDER_NAME: 'Boxing Center',
};

console.log('=== BOXING CENTER BOT — BOTHOSTING ===');

function envLine(key, value) {
    if (value === undefined || value === null || value === '') return null;
    const v = String(value);
    if (/[\s#"'\\=]/.test(v)) {
        return `${key}="${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
    }
    return `${key}=${v}`;
}

function buildEnvContent() {
    const lines = ['# Auto-generated by bothosting-index.js', `# ${new Date().toISOString()}`, ''];
    for (const key of ENV_KEYS) {
        const value = process.env[key] ?? DEFAULTS[key];
        const line = envLine(key, value);
        if (line) lines.push(line);
    }
    return `${lines.join('\n')}\n`;
}

function runCommand(cmd, cwd = __dirname) {
    console.log(`> ${cmd}`);
    try {
        execSync(cmd, { cwd, stdio: 'inherit' });
        return true;
    } catch (error) {
        console.error(`Erreur: ${error.message}`);
        return false;
    }
}

function printPublicUrl(port) {
    try {
        const https = require('https');
        https
            .get('https://api.ipify.org', (res) => {
                let data = '';
                res.on('data', (chunk) => {
                    data += chunk;
                });
                res.on('end', () => {
                    const ip = data.trim();
                    console.log('\n==================================================');
                    console.log('URL API BOT (pour Vercel BC_API_BASE) :');
                    console.log(`  http://${ip}:${port}`);
                    console.log('Variable Vercel : BC_API_BASE=http://IP:PORT');
                    console.log('Variable bot    : CORS_ORIGIN=https://votre-app.vercel.app');
                    console.log('==================================================\n');
                });
            })
            .on('error', () => {});
    } catch {
        /* ignore */
    }
}

function validateRequiredEnv() {
    const missing = [];
    if (!process.env.SUPABASE_SERVICE_ROLE_KEY) missing.push('SUPABASE_SERVICE_ROLE_KEY');
    if (!process.env.SITE_API_SECRET && !process.env.JWT_SECRET) {
        missing.push('SITE_API_SECRET ou JWT_SECRET');
    }
    if (!process.env.SUPER_ADMIN_PASSWORD) missing.push('SUPER_ADMIN_PASSWORD');
    if (!process.env.BREVO_API_KEY) {
        console.warn('⚠️  BREVO_API_KEY absent — les emails ne partiront pas.');
    }
    if (missing.length) {
        console.error('❌ Variables Bothosting manquantes :', missing.join(', '));
        console.error('   Configurez-les dans le panneau Bothosting avant de relancer.');
        process.exit(1);
    }
}

function hasPm2() {
    try {
        execSync('pm2 -v', { stdio: 'ignore' });
        return true;
    } catch {
        return false;
    }
}

function startWithPm2() {
    const ecosystem = `module.exports = {
  apps: [{
    name: ${JSON.stringify(PM2_APP_NAME)},
    script: './index.js',
    cwd: ${JSON.stringify(APP_DIR)},
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '400M',
    env: { NODE_ENV: 'production' },
  }],
};
`;
    fs.writeFileSync(path.join(APP_DIR, 'ecosystem.config.js'), ecosystem, 'utf8');
    runCommand('pm2 startOrRestart ecosystem.config.js', APP_DIR);
    runCommand(`pm2 save`, APP_DIR);
    console.log(`✅ Bot démarré sous PM2 (${PM2_APP_NAME}). Commandes : pm2 status | pm2 logs`);
}

function startWithNode() {
    console.log('⚠️  PM2 non détecté — démarrage Node direct.');
    process.chdir(APP_DIR);
    require(path.join(APP_DIR, 'index.js'));
}

async function bootstrap() {
    validateRequiredEnv();

    const port = process.env.PORT || DEFAULTS.PORT;
    printPublicUrl(port);

    if (!fs.existsSync(APP_DIR)) {
        console.log(`\n📂 Clone ${GITHUB_REPO_URL} ...`);
        if (!runCommand(`git clone ${GITHUB_REPO_URL} ${APP_DIR_NAME}`)) {
            process.exit(1);
        }
    } else {
        console.log('\n🔄 Mise à jour du dépôt...');
        runCommand('git pull', APP_DIR);
    }

    console.log('\n⚙️  Génération .env ...');
    fs.writeFileSync(path.join(APP_DIR, '.env'), buildEnvContent(), 'utf8');
    console.log('✅ .env créé dans', path.join(APP_DIR, '.env'));

    console.log('\n📦 npm install ...');
    if (!runCommand('npm install --omit=dev', APP_DIR)) {
        process.exit(1);
    }

    console.log('\n🚀 Démarrage du bot Boxing Center...');
    if (hasPm2()) {
        startWithPm2();
    } else {
        startWithNode();
    }
}

bootstrap().catch((err) => {
    console.error(err);
    process.exit(1);
});
